ALTER TABLE fico_sourced_customers
	add COLUMN `full_name` varchar(100) DEFAULT NULL AFTER kasasa_master_person_id,
	add COLUMN `first_name` varchar(50) DEFAULT NULL AFTER full_name,
	add COLUMN `middle_name` varchar(30) DEFAULT NULL AFTER first_name,
	add COLUMN `last_name` varchar(50) DEFAULT NULL AFTER middle_name,
	add COLUMN `suffix` varchar(10) DEFAULT NULL AFTER last_name,
	add COLUMN `address_1` varchar(100) DEFAULT NULL AFTER suffix,
	add COLUMN `address_2` varchar(100) DEFAULT NULL AFTER address_1,
	add COLUMN `city` varchar(50) DEFAULT NULL AFTER address_2,
	add COLUMN `state` char(2) DEFAULT NULL AFTER city,
	add COLUMN `zipcode` varchar(5) DEFAULT NULL AFTER state,
	add COLUMN `zipcode_extended` varchar(4) DEFAULT NULL AFTER zipcode,
	add COLUMN `delivery_point_bar_code` int(11) DEFAULT NULL AFTER zipcode_extended,
	add COLUMN `carrier_route_code` varchar(10) DEFAULT NULL AFTER delivery_point_bar_code,
	add COLUMN `line_of_travel` varchar(10) DEFAULT NULL AFTER carrier_route_code,
	add COLUMN `national_change_of_address_move_flag` char(1) DEFAULT NULL AFTER line_of_travel,
	add COLUMN `national_change_of_address_move_date` date DEFAULT NULL AFTER national_change_of_address_move_flag,
	add COLUMN `national_change_of_address_drop_flag` char(1) DEFAULT NULL AFTER national_change_of_address_move_date,
	add COLUMN `email` varchar(100) DEFAULT NULL AFTER national_change_of_address_drop_flag,
	add COLUMN `email_append_flag` char(1) DEFAULT NULL AFTER email
;