version: '3'
services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=local_root_password
      - MYSQL_USER=local_admin
      - MYSQL_PASSWORD=local_admin_password
    ports:
      - 3306:3306
  runner:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - MYSQL_HOST=db
      - MYSQL_ROOT=root
      - MYSQL_ROOT_PASSWORD=local_root_password
      - MYSQL_PORT=3306
      - MYSQL_USER=local_admin
      - MYSQL_PASSWORD=local_admin_password
    depends_on:
      - db