FROM 304872096477.dkr.ecr.us-west-2.amazonaws.com/kasasa/python:3.7

WORKDIR /app

COPY ./requirements.txt .
COPY ./requirements.test.txt .
COPY ./run_tests.sh .
RUN pip3 install --upgrade pip \
    && pip3 install -r requirements.test.txt

COPY ./app .
COPY ./tests ./tests

ENTRYPOINT ["./run_tests.sh"]